### ISSUE TITLE
If a word has an article on wikipedia parser is failing to remove those texts

### ISSUE THREAD

**Issue by Praveena0989** [Suyash458/WiktionaryParser#10]
Hello,

If a word has an article on wikipedia then parser will include that title in text field of definition.
Ex:  try parsing `alexin`

As of now i am solving this like this
`        definition['text']=[s for s in definition['text'].splitlines() if s and not ((s.lower() == 'wikipedia') or s.lower().startswith('wikipedia has an'))]
`

**Comment by Suyash458** [comment]
Thanks! Fixed it for now in 2e755f40dbfdcdb6bdd74c1b3dcb45071698cee2

**Comment by Praveena0989** [comment]
It is failing in python 3.

**Comment by Suyash458** [comment]
I tried it on Python 3.6 and don't see any issues. Is there a specific word which is failing?
