### ISSUE TITLE
ImportError: No module named 'utils'

### ISSUE THREAD

**Issue by kungming2** [Suyash458/WiktionaryParser#17]
After updating to 0.0.4, I regularly get this error when I attempt to import the module WiktionaryParser.

**Comment by Suyash458** [comment]
Are you using Python 3? I tried importing it and it worked fine. Probably an issue with Python 2?

**Comment by kungming2** [comment]
Yeah, I was using Python 3.5. Tested on two different machines with the same result - a macOS system and a RPi3 running Raspian. Deleting the utils import and copying its data into WikiParse.py solved it but as such a clean installation from PyPI doesn't work for me.

**Comment by Suyash458** [comment]
Ah my bad, just saw it.
Change line 7 in WikiParse.py to 
`from wiktionaryparser.utils import WordData, Definition, RelatedWord`

That should make it work, I'll update the package soon.

**Comment by kungming2** [comment]
Fantastic, thanks for the quick response!

**Comment by fmv1992** [comment]
Issue still persists if installed via pip3:

```
Using cached wiktionaryparser-0.0.4-py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/
```

But it does not if installed with clone and python3:

```
➜  /tmp git clone --recursive 'https://github.com/Suyash458/WiktionaryParser'         
Cloning into 'WiktionaryParser'...
[...]
➜  WiktionaryParser git:(master) python3 setup.py install
running install
running bdist_egg
[...]
Extracting wiktionaryparser-0.1-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding wiktionaryparser 0.1 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/wiktionaryparser-0.1-py3.6.egg
Processing dependencies for wiktionaryparser==0.1
Finished processing dependencies for wiktionaryparser==0.1
```

Please update the package in PyPi. It still shows 0.0.4: https://pypi.python.org/pypi/wiktionaryparser/0.0.4

I'm using this as a dependency for one of my projects :)

**Comment by Suyash458** [comment]
I've updated the package in PyPi, let me know if it works.
