### ISSUE TITLE
As of 0.0.6, WikiParse.py is no longer included in the package.

### ISSUE THREAD

**Issue by abendebury** [Suyash458/WiktionaryParser#25]
With 0.0.5:

`% ls /home/alexei/.virtualenvs/4ivn7uXV/lib/python3.5/site-packages/wiktionaryparser
WikiParse.py  __init__.py  __pycache__  tests.py  utils.py`

With 0.0.6:

`% ls /home/alexei/.virtualenvs/4ivn7uXV/lib/python3.5/site-packages/wiktionaryparser
__pycache__  setup.py`

This, of course, breaks the package so it cannot be used, since the package code is not included.

**Comment by Suyash458** [comment]
Fixed now
