### ISSUE TITLE
not all existing relations are returned

### ISSUE THREAD

**Issue by ookimi** [Suyash458/WiktionaryParser#27]
Example query: for the word "white", querying English Wikipedia does not return derived words for the noun part-of-speech. In the entry for "boy", this relation is parsed correctly.

**Comment by C0rn3j** [comment]
I kind of created a dupe of this issue on accident, and it has been fixed. You may want to retest and close this issue ^^

https://github.com/Suyash458/WiktionaryParser/issues/33
