### ISSUE TITLE
Support for parsing inflections

### ISSUE THREAD

**Issue by C0rn3j** [Suyash458/WiktionaryParser#30]
Definitions on Wiktionary can come with inflections, as in this screenshot:

![image](https://user-images.githubusercontent.com/1641362/42351585-149b7988-80b6-11e8-9427-74f6a746bc8f.png)

Raw entry from WitkionaryParser:
```
fly (imperative fly, present tense flyr, simple past fløy, past participle flydd or fløyet)

to fly
```

What I'd like to see parsed:
```
Inflection: [imperative] fly
Inflection: [present tense] flyr
Inflection: [simple past] fløy
Inflection: [past participle] flydd
Inflection: [past participle] fløyet

Word definition:
to fly
```

My use case is creating a dictionary with inflection support (for e-readers like Kindle).

I've worked around this limitation in [my scripts](https://gitlab.com/C0rn3j/C0rn3j/blob/master/NOtoENdict/WiktionaryScrap/json2txt_inf.php#L121-183) but it'd be nice if I didn't have to and it was supported.

EDIT: This needs so many workarounds and has so many edge cases I wouldn't be surprised this never gets implemented as out of scope >.>

**Comment by wmshort** [comment]
I agree that this would be a very useful feature, but given that the inflection systems of languages are so different, probably this is best dealt with at the application rather than module level. Norwegian might have the listed inflection classes (imperative, present tense, simple past) but neither these classes nor their names can be guaranteed for every language -- perhaps not even across different contributors to the same language ('simple past' = 'preterite' for some people, etc.)

**Comment by C0rn3j** [comment]
After dealing with this for a while I'm inclined to agree. There's just too many edge cases I'm aware of and that's just Norwegian.

Feel free to close this as out of scope.

**Comment by wmshort** [comment]
On the other hand some languages -- like Latin -- have fully worked out inflectional paradigms for each entry. This could be very useful to include in the parsed dict, but again there is not much consistency even for lemmas of the same language. Maybe an option to try to include the 'inflection' section where applicable.

As an example, see the 'inflection' section for this Latin entry:

https://en.m.wiktionary.org/wiki/pango

Do many other languages include this info?

William Michael Short
Lecturer in Classics
Department of Classics & Ancient History
University of Exeter

________________________________
