### ISSUE TITLE
Some words get partially scrapped from other language than the defined one

### ISSUE THREAD

**Issue by C0rn3j** [Suyash458/WiktionaryParser#34]
Point in case, trying to scrap Admiral in Norwegian Bokmål yields this:
```
[
  {
    "etymology": "From Arabic أَمِير الْبَحْر‎ (ʾamīr al-baḥr, “commander of the fleet”), via French amiral",
    "definitions": [
      {
        "partOfSpeech": "noun",
        "text": "admìrāl m (Cyrillic spelling адмѝра̄л)\n\nadmiral\n",
        "relatedWords": [],
        "examples": []
      }
    ],
    "pronunciations": {
      "text": [],
      "audio": []
    }
  }
]
```

But that Definition is from Serbo-Croatian instead.

https://en.wiktionary.org/wiki/admiral#Norwegian_Bokm%C3%A5l

**Comment by Suyash458** [comment]
Maybe try the dev branch to see if these problems are fixed? I'll merge it with master later

**Comment by C0rn3j** [comment]
I thought it'd be more words but this is the only instance I was able to find (the cyrillic letters stand out), so there's not any tests I can do that you didn't do already.
