### ISSUE TITLE
Add support for 'Alternative forms'?

### ISSUE THREAD

**Issue by wmshort** [Suyash458/WiktionaryParser#35]

**Comment by C0rn3j** [comment]
Providing an example will probably be more helpful

**Comment by Suyash458** [comment]
Added a feature in 8869866488536b4f32f83cbf800b0c219743a7b9 to include/exclude relations/parts of speech. 

Try ```parser.include_relation('alternative forms')```

**Comment by wmshort** [comment]
Brilliant, this should automatically work for 'derived terms' as well. Thank you!

William Michael Short
Lecturer in Classics
Department of Classics & Ancient History
University of Exeter

________________________________

**Comment by Suyash458** [comment]
You're welcome!
