### ISSUE TITLE
Misparsing of Ancient Greek pronunciations?

### ISSUE THREAD

**Issue by wmshort** [Suyash458/WiktionaryParser#37]
Given a page like this:

https://en.wiktionary.org/wiki/%E1%BC%80%CE%B3%CE%B3%CE%B5%CE%BB%CE%AF%CE%B1#Ancient_Greek

the parser returns:

[
    {
        "etymology": "From \u1f04\u03b3\u03b3\u03b5\u03bb\u03bf\u03c2 (\u00e1ngelos, \u201cmessenger\u201d) +\u200e -\u1fd0\u0301\u1fb1 (-\u00ed\u0101, abstract noun suffix).\n",
        "definitions": [
            {
                "partOfSpeech": "noun",
                "text": "\u1f00\u03b3\u03b3\u03b5\u03bb\u1fd0\u0301\u1fb1 \u2022 (angel\u00ed\u0101)\u00a0f (genitive \u1f00\u03b3\u03b3\u03b5\u03bb\u1fd0\u0301\u1fb1\u03c2); first declension\nmessage, news, report\nAlso, the substance or means of such communication\ninstruction, command\n",
                "relatedWords": [],
                "examples": []
            }
        ],
        "pronunciations": {
            "text": [
                "\u1f00\u03b3\u03b3\u03b5\u03bb\u1fd0\u0301\u1fb1 \u2022 (angel\u00ed\u0101)\u00a0f (genitive \u1f00\u03b3\u03b3\u03b5\u03bb\u1fd0\u0301\u1fb1\u03c2); first declension"
            ],
            "audio": []
        }
    }
]

where the 'pronunciations'.'text' entry is (basically) the same as the 'definitions'.'text' entry.

**Comment by Suyash458** [comment]
Looks fixed in 2ba2eea7d34d8e2ae57633210e648f6054d600ab. Please update to v0.0.93

**Comment by wmshort** [comment]
Many thanks. Will do so ASAP and put it to work! Thank you again for all your work. If there is anything I can do please let me know.

William Michael Short
Lecturer in Classics
Department of Classics & Ancient History
University of Exeter

________________________________
