### ISSUE TITLE
Wrong repo format 

### ISSUE THREAD

**Issue by Narsil** [Suyash458/WiktionaryParser#39]
It seems this repo is not in the correct format breaking some standard usage:

https://docs.python-guide.org/writing/structure/

Notably it's hard to use locally because of local imports, the setup.py file is missing making installing from github painful.

**Comment by Narsil** [comment]
Actually it solves only one problem.

It is now installable with
` pip install -e git+https://github.com/Suyash458/WiktionaryParser@commit_id#egg`

but I still get problems with relative imports. To check them you can clone a fresh version of this repo.

`git clone https://github.com/Suyash458/WiktionaryParser.git`
`cd WiktionaryParser`
`python3 setup.py test`

This should run correctly but gives:

`ValueError: attempted relative import beyond top-level package`

I am not an expert, but usually the structure puts the setup.py file in the root of the project, and the actual project into a directory (like wiktionaryparser/__init__.py instead of wiktionaryparser.py).
This makes the relative imports behave better.

Actually you probably have that kind of setup to package for pypi, no ? `python setup.py sdist`
https://packaging.python.org/tutorials/packaging-projects/

Am I missing something ?

**Comment by Suyash458** [comment]
You're right, although usually if the entire module is just one file it's alright to put it in the root folder
