### ISSUE TITLE
Is there a way to use a dictionary other than any_language to English? (e.g.: Portuguese to Portuguese)

### ISSUE THREAD

**Issue by fmv1992** [Suyash458/WiktionaryParser#40]
Is there a way to use this parser for a given language to given language definition?

    from wiktionaryparser import WiktionaryParser
    parser = WiktionaryParser()
    print(parser.fetch('seda', 'portuguese'))  # silk in English

Gives me:

    [{'pronunciations': {'audio': ['//upload.wikimedia.org/wikipedia/commons/c/cb/Pt-br-seda.ogg', '//upload.wikimedia.org/wikipedia/commons/c/cb/Pt-br-seda.ogg'], 'text': ['(Portugal) IPA: /ˈse.dɐ/', 'Hyphenation: se‧da']}, 'etymology': 'From Old Portuguese seda, from Latin saeta (“animal hair”).\n', 'definitions': [{'relatedWords': [{'relationshipType': 'derived terms', 'words': ['bicho-da-seda', 'sedoso']}], 'text': 'seda f (plural sedas)\n\n(uncountable) silk (a type of fiber)\na piece of silken cloth or silken clothes\n', 'partOfSpeech': 'noun', 'examples': []}]}]

That is: `silk (a type of fiber)\na piece of silken cloth or silken clothes`. Which is the same from the website: <https://en.wiktionary.org/wiki/seda#Portuguese>.

I would like to give me the Portuguese version:

<https://pt.wiktionary.org/wiki/seda>: `substância filamentosa segregada pelo bicho-da-seda ...`.

I would say that that is not possible because of the hardcoding in the following line:

    self.url = "https://en.wiktionary.org/wiki/{}?printable=yes"

But I'm waiting for your opinion on that.

I'm using this project on my own project: <https://github.com/fmv1992/vim_dictionary>. Thanks for the good work!

**Comment by Suyash458** [comment]
You could changing the URL in a fork, a lot of them (Chinese for example) have different page structures so I'm not sure if the parser will break

**Comment by fmv1992** [comment]
Indeed they have different structures... I thought they could use the same under the hood so that english could be used for all of them.

For example:

<https://fa.wiktionary.org/wiki/%DA%AF%D9%84>
(flower)

Instead of "Noun" you have "اسم", and this is hard coded in the html part of the page:


    <li class="toclevel-2 tocsection-3"><a href="#اسم"><span class="tocnumber">۱.۲</span> <span class="toctext">اسم</span></a></li>


Thanks for your answer; I'm closing this issue.
