### ISSUE TITLE
Pronunciations are not parsed

### ISSUE THREAD

**Issue by raffam** [Suyash458/WiktionaryParser#41]
I am trying to fetch the english definition for "to grapple".
In the botto of this message there is the result of the fect. As you can see, the pronunciation section is empty, but the [original page](https://en.wiktionary.org/wiki/grapple) contain the pronunciation. It may be related to the fact that WiktionaryParser puts the pronunciation inside the etimology, while in the original page the pronunciation is outside.

**Comment by Suyash458** [comment]
Yeah that's exactly what's happening, so if the pronunciation is outside I'm gonna assume it applies to all the etymologies

**Comment by raffam** [comment]
Ok, thanks.
So actually WiktionaryParser does not parse them if they are outside. Right?

**Comment by Suyash458** [comment]
Yeah, right now they aren't included

**Comment by Suyash458** [comment]
Should be fixed in 6e2643526b1012b2ad7fb0f281af7eef2b847d48
