### ISSUE TITLE
Examples are not parsed correctly

### ISSUE THREAD

**Issue by raffam** [Suyash458/WiktionaryParser#42]
I am trying to fetch the english definition for "to grapple".
When doing so, wiktionary parses the examples incorrectly. In particular, in the first row there are all the examples separated by a '\n', and then from the second row on the same examples are repeated:

>                 "examples": [
>                     "to grapple with one's conscience",
>                     "Hakluyt\nThe gallies were grappled to the Centurion.Shakespeare\nGrapple them to thy soul with hoops of steel.",
>                     "The gallies were grappled to the Centurion.",
>                     "Grapple them to thy soul with hoops of steel."
>                 ],

**Comment by Suyash458** [comment]
Should be fixed in 6e2643526b1012b2ad7fb0f281af7eef2b847d48
