### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by raffam** [Suyash458/WiktionaryParser#43]
`python -m WiktionaryParser.tests.test
Testing "patronise" in English
Testing "test" in English
F
======================================================================
FAIL: test_multiple_languages (__main__.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\RMANCUSO00\Documents\progetti_miei\WiktionaryParser\tests\test.py", line 24, in test_multiple_languages
    self.assertEqual(DeepDiff(parsed_word, sample_output[lang][word], ignore_order=True), {})
AssertionError: {'values_changed': {"root['etymology']": {[1187 chars].'}}} != {}

----------------------------------------------------------------------
Ran 1 test in 2.157s

FAILED (failures=1)`

I also don't understand what the test is supposed to test?

**Comment by Suyash458** [comment]
Should be fixed in 6e2643526b1012b2ad7fb0f281af7eef2b847d48
