### ISSUE TITLE
Fix and improve tests

### ISSUE THREAD

**Issue by sehwol** [Suyash458/WiktionaryParser#59]
- Fix broken tests
- Split single test that tests all languages into parameterized tests that test 1 word only

**Comment by sehwol** [comment]
Ok. Please do comment if the tests pass/fail on your machine.

**Comment by Suyash458** [comment]
Tests are indeed failing on my machine, I'll probably add mocks that serve local copies of the HTML later

**Comment by sehwol** [comment]
I'll rebase the *testingOutput.json* commits.

> 
> 
> Tests are indeed failing on my machine, 

Sorry, are the tests failing on the pull-request branch or `master`?

>
>
> I'll probably add mocks that serve local copies of the HTML later

I'd like to take care of this. So do you think it would be a good for me to create a script that:
- Downloads the necessary HTML files for testing into the repo.
- Save them as part of the repo.
?

**Comment by Suyash458** [comment]
> > Tests are indeed failing on my machine,
> 
> Sorry, are the tests failing on the pull-request branch or `master`?

Should've been more specific. I meant they're failing on master.

Sure we can have a test utility script that downloads the HTML and saves it as a part of the repo whenever a new test word is added. We'll also have to mock `session.get` to read these HTML files and return them instead
