### ISSUE TITLE
Create a test utility script that downloads test HTML and markdown and saves it as a part of the repo

### ISSUE THREAD

**Issue by sehwol** [Suyash458/WiktionaryParser#62]
Self assigned.

- Setup mocks of the `fetch()` method to use offline files. Leave a few copies of the test as integration tests calling actual Wiktionary, preferably shorter word pages that won't change any time soon.
- Create *scripts/download_wiktionary_test_files.py* that does the following:
  - Download HTML files of all words under test.
  - Download the Markdown files from the API endpoint below

```
https://en.wiktionary.org/w/api.php?action=parse&oldid={{OLDID}}&prop=wikitext&formatversion=2&format=json
```

**Comment by Suyash458** [comment]
So I was thinking we could mock the `session.get` method or use the [responses](https://github.com/getsentry/responses) library as described here 
https://stackoverflow.com/questions/15753390/how-can-i-mock-requests-and-the-response

That way, in the test, the same `fetch()` method would use HTML served locally. What do you think?

**Comment by sehwol** [comment]
> 
> 
> So I was thinking we could mock the `session.get` method or use the [responses](https://github.com/getsentry/responses) library as described here
> https://stackoverflow.com/questions/15753390/how-can-i-mock-requests-and-the-response
> 
> That way, in the test, the same `fetch()` method would use HTML served locally. What do you think?

Sounds good. I'll work on it.
