### ISSUE TITLE
chore: Mild reorganization of project files for better dev experience, tidiness

### ISSUE THREAD

**Issue by sehwol** [Suyash458/WiktionaryParser#64]
Self assigned, if the repo owner gives permission.

I'd like to move *wiktionaryparser.py* and the *utils.py* into a new *wiktionaryparser* folder, making the project structure conform to the structures of other Python repositories.

![proj-structure](https://user-images.githubusercontent.com/50994416/92303418-c52aa900-ef9e-11ea-9e58-655d1e67931c.PNG)

![proj-structure-2](https://user-images.githubusercontent.com/50994416/92303454-2d798a80-ef9f-11ea-88cd-757c6cdc088b.PNG)

I'll make sure to add a *CONTRIBUTING.md* with the shell script contributors can copy paste to get their dev env setup (`venv`, `pip install -e .`). 

I'll also make sure to add the classes in *utils.py* to `__all__` so the API doesn't change.

The aim's just to:
- Make the repo tidier.
- Make Intellisense work again since, for some reason, the current project structure is preventing it from doing autocompletion.
- Pave the way for absolute imports.

**Comment by Suyash458** [comment]
This makes sense. I'd not given much thought to project structure initially. Feel free to submit a PR for this!
