### ISSUE TITLE
Map_to_object() issue for words with more than 8 etymologies

### ISSUE THREAD

**Issue by Luca1152** [Suyash458/WiktionaryParser#69]
The `map_to_object()` function inside `core.py` doesn't work properly when a word has more than 8 etymologies, such as [cat](https://en.wiktionary.org/wiki/cat). Here are the definitions included for all etymologies of this word, as well as the comparisons that are made in the function's code:

```
Etymology 1
'1.2' <= '1.2.1' < '1.3'
'1.2' <= '1.2.2' < '1.3'

Etymology 2
'1.3' <= '1.3.1' < '1.4'

Etymology 3
'1.4' <= '1.4.1' < '1.5'
'1.4' <= '1.4.2' < '1.5'

Etymology 4
'1.5' <= '1.5.1' < '1.6'

Etymology 5
'1.6' <= '1.6.1' < '1.7'

Etymology 6
'1.7' <= '1.7.1' < '1.8'

Etymology 7
'1.8' <= '1.8.1' < '1.9'

Etymology 8

Etymology 9
'1.10' <= '1.2.1' < '999'
'1.10' <= '1.2.2' < '999'
'1.10' <= '1.3.1' < '999'
'1.10' <= '1.4.1' < '999'
'1.10' <= '1.4.2' < '999'
'1.10' <= '1.5.1' < '999'
'1.10' <= '1.6.1' < '999'
'1.10' <= '1.7.1' < '999'
'1.10' <= '1.8.1' < '999'
'1.10' <= '1.9.1' < '999'
'1.10' <= '1.10.1' < '999'
```

whereas the last two etymologies should have been:

```
Etymology 8
'1.10' <= '1.9.1' < '999'

Etymology 9
'1.10' <= '1.10.1' < '999'
```

Since I couldn't quickly find a fix _that would pass all the tests_ and the bug isn't a critical one, I chose to submit an issue here.

**Comment by Suyash458** [comment]
Thanks for reporting this! I'll have a look
