### ISSUE TITLE
Quick question :)

### ISSUE THREAD

**Issue by Piplopp** [Suyash458/WiktionaryParser#8]
Hey, first great job on this project !
I was trying to do the same thing before finding your work. However I was trying to use the provided API. I successfully managed to get the pages I wanted but so far I failed to parse the resulting HTML with BS :sob:

Did you try to use the API or not ? And if yes what made you change to the current method you're using ?
Really good job tho, I try a bit more but I definitely cloned that and will fork it if I add some usefull things in it!

**Comment by Suyash458** [comment]
Hey, thanks!
I did try to use the API but the result has no structure, looks something like [this](https://en.wiktionary.org/w/api.php?format=json&action=query&titles=don%27t&rvprop=content&prop=revisions&redirects=1). Try getting the entire page in HTML and then parse the content from different tags, that's what I did.

**Comment by Piplopp** [comment]
Well, after hours reading this API docs I manage to get [this](https://en.wiktionary.org/w/api.php?action=parse&page=bioinformatics&prop=text). So I will try to parse it using your code and if I succeed I'll run some benchmarks (I think pycurl may be faster than response but more difficult to use too, I'll do some checks when I have some spare time)

**Comment by Suyash458** [comment]
Sure, that sounds good.
